import { apiFetch } from './index'

export const testApi = () => apiFetch('/api/test', {method: 'POST'})
export const getAllDevices = () => apiFetch('/api/get_all_devices', {method: 'POST'})
export const getRawIngest = (body) => apiFetch('/api/get_raw_ingest', { method: 'POST', body: JSON.stringify(body) })
export const reprocessIngest = (body) => apiFetch('/api/reprocess_raw_ingest', { method: 'POST', body: JSON.stringify(body) })
export const getPost = (id) => apiFetch(`/posts/${id}`)
export const createPost = (body) => apiFetch('/posts', { method: 'POST', body: JSON.stringify(body) })
export const createDeviceProfile = (body) => apiFetch('/api/create_device_profile', { method: 'POST', body: JSON.stringify(body) })
export const updateDeviceProfile = (body) => apiFetch('/api/update_device_profile', { method: 'POST', body: JSON.stringify(body) })
export const deleteDeviceProfile = (body) => apiFetch('/api/delete_device_profile', { method: 'POST', body: JSON.stringify(body) })
export const getDeviceProfiles = () => apiFetch('/api/get_device_profiles', { method: 'POST' })
export const getProcessedData = (body) => apiFetch('/api/get_processed_data', { method: 'POST', body: JSON.stringify(body) })
export const getServerConfig = () => apiFetch('/api/get_server_config', { method: 'POST' })
export const createDevice = (body) => apiFetch('/api/create_device', { method: 'POST', body: JSON.stringify(body) })
export const updateDevice = (body) => apiFetch('/api/update_device', { method: 'POST', body: JSON.stringify(body) })
export const deleteDevice = (body) => apiFetch('/api/delete_device', { method: 'POST', body: JSON.stringify(body) })
export const saveDashboard = (body) => apiFetch('/api/save_dashboard', { method: 'POST', body: JSON.stringify(body) })
export const getDashboard = (body) => apiFetch('/api/get_dashboard', { method: 'POST', body: JSON.stringify(body) })
export const deleteDashboard = (body) => apiFetch('/api/delete_dashboard', { method: 'POST', body: JSON.stringify(body) })
export const getDashboards = () => apiFetch('/api/get_dashboards', { method: 'POST' })
export const getDeviceSuccessfulIngest = (body) => apiFetch('/api/get_device_successful_ingest', { method: 'POST', body: JSON.stringify(body) })
export const getDashboardMetric = (body) => apiFetch('/api/get_dashboard_metric', { method: 'POST', body: JSON.stringify(body) })